//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLAgain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SQLAgain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table id=&quot;t03&quot;&gt;&lt;tr&gt;&lt;td&gt;&lt;br&gt;&lt;br&gt; 
        ///SQLAgain is a Tool to execute SQL-Files against 1 or n Oracle Databases using predefined Database 
        ///Users and simplified SQL*Plus formatting Options. 
        ///&lt;br&gt; 
        ///It runs as a.NET Application, either in Foreground or as a scheduled Task in Background. 
        ///&lt;br&gt; 
        ///.NET 4.x and Oracle SQL*Plus are required. 
        ///&lt;br&gt;&lt;br&gt; 
        ///Let me know if you have any questions. 
        ///&lt;br&gt; 
        ///martin.bruegger@gmail.com  
        ///&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt; &lt;/td&gt;&lt;/tr&gt; &lt;/table&gt;.
        /// </summary>
        internal static string MailFooter {
            get {
                return ResourceManager.GetString("MailFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;style&gt; 
        ///* { font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size:1em ; }
        ///BODY { background-color: White; color: black; max-width: 700px; min-width: 300px;} 
        ///h3 { margin-top: 10pt; }
        ///table { width: 100%; border-collapse: collapse; padding: 5px; font-size:10pt;} 
        ///table td { display: table-cell; vertical-align: top; text-align: left; border: 0; background-color:white;  } 
        ///table th { width: 1%; white-space: nowrap;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailHeader {
            get {
                return ResourceManager.GetString("MailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Update {
            get {
                object obj = ResourceManager.GetObject("Update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
